### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by mrubioroy** [darkdragon-001/offlinefs#2]
Compile instructions don't work as described in README.md

First step should be `libtoolize`, then `aclocal`, not the other way round. Otherwise the `m4` directory doesn't exist and `aclocal` complains.

Secondly, `automake --add-missing` fails if the README file doesn't exist. Renaming README.md to README makes it work.

The rest works correctly down to install.

**Comment by darkdragon-001** [comment]
@mrubioroy Thanks for your hints. I added a rule to `./Makefile.am` to generate README from README.md to that autotools no longer complains but github still parses this file correclty...
