### ISSUE TITLE
Windows support (alternative to "Windows Offline Files")

### ISSUE THREAD

**Issue by dumblob** [darkdragon-001/offlinefs#7]
This sounds like an interesting alternative to "Windows Offline Files" if used with https://github.com/billziss-gh/winfsp .

Why? Because "Windows Offline Files" are very unreliable and full of issues with synchronisation (connection detection, bandwidth, latency, ...), conflicts, etc.

The use case would be to mount remote Samba shares as a local drive (by default it would just delegate all requests transparently in boths ways and if the network connection wouldn't be available, then also no data would be available) and then to select some arbitrary files or directories which shall be also available offline (one could even add a shortcut with `C:\path\to\offlinefs\client.exe --make-available-offline -- %*` to the "Send to" context submenu which would update the internal list of files and directories which shall be available offline).

This is exactly the scenario which is most common in thousands of enterprises over the world as the people need access to all data if they are on site, but because they're often off site, they need some chosen data (usually just few gigabytes, but not the company terabytes) even without internet connection.

@billziss-gh, what would you think?

**Comment by dumblob** [comment]
There might be some need to make the list of conflicts graphical (allowing easy and user-friendly resolution), but that's a minor issue for the beginning.

What is actually the `dbus` dependency needed for?

**Comment by billziss-gh** [comment]
From a brief look into this project, it appears to use POSIX API's and high-level FUSE. A port using Cygwin and "FUSE for Cygwin" (bundled with WinFsp) should be possible.

(BTW, Cygwin seems to support dbus.)

If a port attempt is made, I am happy to support it.

**Comment by darkdragon-001** [comment]
This seems to be an interesting approach!

I am open to restructure the code to share the common, operating system independent parts and split the operating system specific parts.

**Comment by darkdragon-001** [comment]
I am happy to accept pull requests. Closing this issue as it is out of scope for myself.

**Comment by dumblob** [comment]
Ok, I'll spread the word if anyone would have the time for this.

**Comment by darkdragon-001** [comment]
@dumblob To be honest, [Windows' new Cloud Files API](https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine) is awesome (much better than _Windows Offline Files_!) and was exactly what I had in mind when I was searching for OfflineFS in the first place (see integration for [Nextcloud](https://nextcloud.com/blog/nextcloud-desktop-client-3-2-with-status-feature-and-virtual-files-available-now/), [Seafile](https://blogs.seafile.com/2020/08/08/seafile-drive-client-2-0-next-generation-alternative-to-traditional-file-servers/)). Actually my long-term goal is to create a similar API on Linux. So I expect the benefit of porting OfflineFS to Windows very limited. Would be much better to create a separate app using the Windows API directly.

**Comment by dumblob** [comment]
@darkdragon-001 thanks for pointing it out - I completely missed the new Cloud Files API. That really totally reshuffles the cards and I agree with you it'd be better to have a separate app for that.

OTOH I wonder if the new API has made sync apps more stable (compared to the horrible experience with "Windows Offline Files"). If you have some recent information about such experience, feel free to share it!

**Comment by darkdragon-001** [comment]
@dumblob I stopped using Windows myself five years ago, so unfortunately, I don't have any experience with the new API. It's just my favorite apps implement this feature on Windows and I would like similar functionality on Linux :rofl:
